id: D8B94A4B1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T07:57:42+00:00'
last_modified: '2022-05-26T06:01:45.102008+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    a164:
      image_group_id: I1PD95846
      title: ཆོས་ཀྱི་དབྱིངས་སུ་བསྟོད་པ།
      total_pages: 1539
      order: 1
      base_file: a164.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
