id: efbdd5d677cc4bf68785191c51ed0d80
initial_creation_type: ocr
source_metadata:
  volumes:
    1b149a1a22564ead9c0b6f85a22c96b3:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: ཆོས་ཀྱི་དབྱིངས་སུ་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
